name: Java Program

on: [ push, pull_request]
jobs:
 job1:
   runs-on: ubuntu-latest
   container: 
         image: openjdk:17-jdk-slim
   steps:
         - uses: actions/checkout@v4
         - name: java compile
           run: |
                javac Hello.java
                echo "Complied Hello.class"
         - name: upload artifact
           uses: actions/upload-artifact@v3
           with:
              name: Hello-class
              path: Hello.class
 job2:
     runs-on: ubuntu-latest
     container: 
         image: openjdk:17-jdk-slim            
           
    

