name: Java Program

on: [ push, pull_request]
jobs:
 job1:
   runs-on: ubuntu-latest
   container: 
         image: openjdk:17-jdk-slim
   steps:
         - uses: actions/checkout@v4
         - name: java compile
           run: |
                javac Hello.java
                echo "Complied Hello.class"
         - name: upload artifact
           uses: actions/upload-artifact@v3
           with:
              name: Hello-class
              path: Hello.class
 job2:
     runs-on: ubuntu-latest
     container: 
         image: openjdk:17-jdk-slim            
     needs: compile 
     steps:
      - uses: actions/checkout@v4
      - name: Download Class File
        uses: actions/download-artifact@v3
        with:
              name: Hello-class
      - name: Run Java Program
        run: java hello
  
 job3:
    runs-on: ubuntu-latest
    steps:
     - name: Download Class File
       env:
        MY_VAR: "MY Variable"
       run: echo $MY_VAR 
      
     
    

